//CREATE DATABASE
CREATE DATABASE POC_1_DATABASE;

USE DATABASE POC_1_DATABASE;

//CREATE SCHEMA
CREATE SCHEMA POC_1_SCHEMA;

//ENABLE MANAGED ACCESS IN SCHEMA
ALTER SCHEMA POC_1_DATABASE.POC_1_SCHEMA
ENABLE MANAGED ACCESS;