USE ROLE SYSADMIN;

CREATE OR REPLACE USER ADMIN_USER
LOGIN_NAME = 'ADMIN' PASSWORD = 'ADMIN'
DEFAULT_ROLE = LOCAL_ADMIN_ROLE
DEFAULT_WAREHOUSE = POC_1_WH;

USE ROLE SECURITYADMIN;

GRANT ROLE LOCAL_ADMIN_ROLE TO USER ADMIN_USER;