USE ROLE LOCAL_ADMIN_ROLE;

//CREATE ROLES
CREATE ROLE DEVELOPER_ROLE;
CREATE ROLE ANALYST_ROLE;

//GRANT ROLES AND USAGES
GRANT ROLE DEVELOPER_ROLE TO ROLE LOCAL_ADMIN_ROLE;
GRANT ROLE S_WRITE, D_USAGE TO ROLE DEVELOPER_ROLE;
GRANT USAGE ON WAREHOUSE POC_1_WH TO ROLE DEVELOPER_ROLE;

GRANT ROLE ANALYST_ROLE TO ROLE LOCAL_ADMIN_ROLE;
GRANT ROLE S_READ, D_USAGE TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE POC_1_WH TO ROLE ANALYST_ROLE;

//CREATE DEV AND ANALYST USERS
CREATE OR REPLACE USER DEVELOPER
LOGIN_NAME = 'DEV' PASSWORD = 'DEV'
DEFAULT_ROLE = DEVELOPER_ROLE
DEFAULT_WAREHOUSE = POC_1_WH;

CREATE OR REPLACE USER ANALYST
LOGIN_NAME = 'ANL' PASSWORD = 'ANL'
DEFAULT_ROLE = ANALYST_ROLE
DEFAULT_WAREHOUSE = POC_1_WH;

//GRANT ROLES TO USERS
GRANT ROLE DEVELOPER_ROLE TO USER DEVELOPER;
GRANT ROLE ANALYST_ROLE TO USER ANALYST;
