USE ROLE USERADMIN;

--CREATE ACCESS ROLES
CREATE ROLE S_READ;
CREATE ROLE S_WRITE;
CREATE ROLE S_FULL;
CREATE ROLE D_USAGE;
CREATE ROLE D_FULL;

--CREATE LOCAL_ADMIN_ROLE
CREATE ROLE LOCAL_ADMIN_ROLE;

USE ROLE SECURITYADMIN;

--S_READ
GRANT USAGE ON SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_READ;

--S_WRITE
GRANT MODIFY, MONITOR, USAGE, CREATE TABLE, CREATE EXTERNAL TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT
ON SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_WRITE;

--S_FULL WITH HIERARCHY
GRANT MODIFY, MONITOR, USAGE, CREATE TABLE, CREATE EXTERNAL TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE MASKING POLICY, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT, CREATE STAGE, CREATE PIPE, CREATE STREAM, CREATE TASK ON SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_FULL;
GRANT ALL ON ALL TABLES IN SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_FULL;
GRANT ALL ON FUTURE TABLES IN SCHEMA POC_1_DATABASE.POC_1_SCHEMA TO ROLE S_FULL;

GRANT OWNERSHIP ON ROLE S_READ TO ROLE S_FULL;
GRANT OWNERSHIP ON ROLE S_WRITE TO ROLE S_FULL;

GRANT ROLE S_READ TO ROLE S_FULL;
GRANT ROLE S_WRITE TO ROLE S_FULL;

--D_USAGE
GRANT USAGE ON DATABASE POC_1_DATABASE TO ROLE D_USAGE;

--D_FULL WITH HIERARCHY
GRANT USAGE,MODIFY,MONITOR,CREATE SCHEMA ON DATABASE POC_1_DATABASE TO ROLE D_FULL;

GRANT OWNERSHIP ON ROLE S_FULL TO ROLE D_FULL;
GRANT OWNERSHIP ON ROLE D_USAGE TO ROLE D_FULL;

GRANT ROLE S_FULL TO ROLE D_FULL;
GRANT ROLE D_USAGE TO ROLE D_FULL;


--LOCAL_ADMIN_ROLE WITH HIERARCHY
GRANT ROLE LOCAL_ADMIN_ROLE TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE POC_1_WH TO ROLE LOCAL_ADMIN_ROLE WITH GRANT OPTION;

GRANT OWNERSHIP ON ROLE D_FULL TO ROLE LOCAL_ADMIN_ROLE;
GRANT ROLE D_FULL TO ROLE LOCAL_ADMIN_ROLE;


USE ROLE ACCOUNTADMIN;

--GRANT PRIVILEGE TO CREATE ROLES AND USERS
GRANT CREATE ROLE ON ACCOUNT TO ROLE LOCAL_ADMIN_ROLE;
GRANT CREATE USER ON ACCOUNT TO ROLE LOCAL_ADMIN_ROLE;
